### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: $CryptoJS

### ISSUE THREAD

**Issue by SevymolSebastian** [tpenaranda/vue-cryptojs#27]
I have installed this module by
`npm install vue-cryptojs`

version:
`"vue-cryptojs": "2.4.5"`
`"vue": "2.7.14"`

Then in main.js

```
import VueCryptojs from 'vue-cryptojs';
Vue.use(VueCryptojs);
```

But when I try to use it on my component

`const encryptedText = this.$CryptoJS.AES.encrypt("Hi There!", "Secret Passphrase").toString()`

Got an error:

```
Uncaught TypeError: Cannot redefine property: $CryptoJS
    at Function.defineProperties (<anonymous>)
    at Object.install (app.js:329626:383)
    at Vue.use (app.js:343911:28)
    at Object.install (app.js:329626:765)
    at Vue.use (app.js:343911:28)
```

Also I gon aerror:
`[Vue warn]: provide() can only be used inside setup().`

How to solve?

**Comment by tpenaranda** [comment]
Mmm... not a Vue expert here, but just a hint... since Vue 2.7 includes composition API, what about using 'setup()' function as the v3 install example? @SevymolSebastian
